---
- name: Install Node Exporter
  hosts: all
  become: yes

  tasks:
    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /usr/sbin/nologin
        system: yes

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract archive
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy binary
      copy:
        src: /tmp/node_exporter-1.9.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and Start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started